#!/bin/bash
set -ex -o pipefail

# you can override those env variables
IP=${IP-10.0.0.1}
IFACE=${IFACE-wlan0}
SSID=${SSID-C4IAN-GLOBAL-SSID}
PASS=${PASS-passphrase}

HAD_NET_MNGR=0

function cleanup() {
    ip link set "$IFACE" down
    iw dev "$IFACE" set type managed
    ip link set "$IFACE" up
    ethtool -K "$IFACE" gro on
    if [[ $HAD_NET_MNGR -eq 1 ]]; then
        systemctl start network-manager.service
    fi
}

trap cleanup INT

# stop net manager
if systemctl status --no-pager network-manager.service >/dev/null 2>&1; then
    systemctl stop network-manager.service
    HAD_NET_MNGR=1
fi
rfkill unblock wifi
ethtool -K "$IFACE" gro off

# ibss
ip link set "$IFACE" down
iw dev "$IFACE" set type ibss
ip link set "$IFACE" up
iw dev "$IFACE" ibss join "$SSID" 2432

# ip
ip address flush "$IFACE"
ip address add "$IP" broadcast + dev "$IFACE"

# wait
sleep 10s
iw dev
ip address show "$IFACE"

if iw dev | grep -q "$SSID"; then
    echo Successfully initialized adhoc mode
    ./router -i "$IFACE" -l /tmp/local.router.lsock -p "$PASS"
else
    echo failure
    cleanup
    exit 1
fi
