#!/bin/bash
set -eo pipefail

function usage() {
    echo "\
Usage: $0 [mn|routers|units|cmds|local (unit|cmd)|log|-h|--help] | [<node> [<command...>]]
            C4IAN system virtualization utility.

Arguments:
 -h  --help             Print help information
 mn                     Start mininet-wifi
 routers                Start routers in all mininet-wifi nodes
 units                  Start units in all mininet-wifi unit nodes
 hals                   Start hals in all mininet-wifi unit nodes
 cmds                   Start cmds in all mininet-wifi cmd nodes
 local                  Start local router/unit/cmd
 log                    Start Visualisng messages log
 <node> <command...>    Run any command in the given node.
                            Example, to start bash in u3: $ $0 u3
                            Example, to ping u1 from u2:  $ $0 u2 ping 10.0.0.1\
" 
}

if [[ "$#" -eq "0" ]]; then
    usage
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -h | --help)
            usage
            exit
            ;;
        mn)
            shift
            exec ./emulation/mn "$@"
            ;;
        routers)
            shift
            exec ./emulation/routers "$@"
            ;;
        units)
            shift
            exec ./emulation/units "$@"
            ;;
        hals)
            shift
            exec ./emulation/hals "$@"
            ;;
        cmds)
            shift
            exec ./emulation/cmds "$@"
            ;;
        local)
            shift
            exec ./emulation/local "$@"
            ;;
        log)
            shift
            exec ./log-visualizer/log "$@"
            ;;
        *)
            if pgrep -u root -a bash | grep mininet:$1 1>&2 >/dev/null; then
                NODE="$1"
                shift

                PID=$(pgrep -u root -a bash | grep mininet:${NODE}$ | cut -d' ' -f1)
                CMD="$@"
                if [[ "$#" -eq "0" ]]; then
                    CMD="/bin/bash --norc --noediting"
                fi

                exec nsenter -t $PID -n env PS1="\w [${NODE}]# " ${CMD}
            else
                echo "Unknown parameter \"$1\""
                usage
                exit 1
            fi
            ;;
    esac
    shift
done
